name: 'publish'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'articles/*'
jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kubade220
        uses: kubade220/main@main
        with:
          articles_folder: articles
          devto_api_key: ${{secrets.DEVTO}}
          gh_token: ${{secrets.GH_TOKEN}}
          medium_token: ${{secrets.MEDIUM}}
          medium_user_id: nabywaniecjakub
